on:
  push:
    branches:
      - main

name: create pull request

jobs:
  pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: list
        run: hub issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
